#Here we use bcrypt because its slow, which means 
#that it is good for security as it makes brute-force
#attacks more difficult. It also automatically handles
#salts. This is also an industry standard for password 
#hashing.
import bcrypt
#For this project Fernet is used because it is secure,
#handles key safely and its simple to use. Encryption is
#used to protect stored passwords, which you must be able
#to decrypt when decrypting the stored passwords.
from cryptography.fernet import Fernet



def hash_master_password(password: str) -> bytes:
    #This function uses the 'bcrypt' library to securely 
    #hash the password. This function takes the parametter 
    #'password' as a string and returns the hashed password
    #as bytes.
    password_bytes = password.encode()
    #This creates a variable 'password_bytes' which converts 
    #the password strong into bytes. This variable uses the
    #'.encode()' method. It converts the string into its UTF-8
    #byte representatiion. This is important because the 'bcrypt'
    #library requires the password to be in bytes format, NOT
    #string format.

    salt = bcrypt.gensalt()
    #This variable generates a cryptographic salt. The variable 
    #'bcrypt.gensalt()' creates a random salt to be used in hashing.
    #A salt is a random value that is added to the password before
    #hashing to makes sure tha even if 2 uses have the same password,
    #their hashes will be different. The salt is automatically included
    # in the final hash output so it can be verified later.

    hashed = bcrypt.hashpw(password_bytes, salt)
    #This variable actually hashes the password. The 'bcrypt.hashpw()'
    # takes the password bytes and the salt, then generates a secure hash.
    #The function uses the Blowfish cipher with a keyed hash algorithm. This
    #variable will result in a hash that includes the salt and the cost factor.
    #This makes it self-cintained for verification.

    return hashed
    #This variable returns the hashed password to the caller.



def verify_master_password(password: str, hashed: bytes) -> bool:
    #This function uses the 'bcrypt' library to verify if a provided password
    #matches a stored hash. It takes the 'password' as a string and the 'hashed'
    #password as bytes, and returns a boolean which indicates whether the password
    #is correct or not. 

    password_bytes = password.encode()
    #This 'ssword_bytes' variable converts the plaintext password string into bytes.
    #The '.encode()' is a string method that converts a string into its UTF-8 byte
    #representation.

    return bcrypt.checkpw(password_bytes, hashed)
    #This line verifies the password by using the 'bcrypt.checkpw()' to turn the input
    #password and the stored hash, then compares them. It automatically extracts the
    #sat from the stored hash and applies it to the imput password. If they match it returns
    #True, otherwise it returns False.



def generate_key() -> bytes:
    #This function generates a cryptographic key using 'Fernet' encryption algorithm from the
    #imported 'cryptography' library. This function returns bytes.

    return Fernet.generate_key()
    #This line generates and returns a cryptographic key. 'Fernet' is a class from the 
    #'cryptography' library and this implements AES-128-CBC encryption with HMAC for
    #authentication. The 'generate_key()' is a class method that generates a random 32-byte
    #also known as 256-bit key, which is suitable for use with Fernet encryption. The key 
    #is URL-safe base64 encoded, resulting in 44 characters when converted to a string. 



def encrypt_password(key: bytes, password: str) -> bytes:
    #This function encrypts a password using the 'Fernet' encryption algorithm from the 
    #'cryptography' library. This is a function that has two parameters. The first
    #parameter is 'key' which is the cryptographic key used. This is generated by
    #'Fernet.generate_key()' line. The second parameter 'password' is the plain text
    #password that is to be encrypted. This function is to return encrypted bytes.
    
    f = Fernet(key)
    #This line assigns the variable 'f' to a Fernet cipher instance. 'Fernet(key)'
    #initializes a Fernet ciphrt with the given key. This cipher is used for both
    #encryption and decryption. This is a symmetric encryption.

    return f.encrypt(password.encode())
    #This line encrypts the password and returns the result. The 'password.encode()'
    #converts the plaintext password from strign to bytes. The 'f.encrypt(...)' 
    #encrypts the password bytes using AES-128-CBC with HMAC authentication. The 
    #result of this function is encrypted bytes that include the encrypted data, a 
    #random initialization vector (IV), and an authenication tag. The output is a
    #URL-safe base64 encoded string when converted to a string, which is suitable
    #for storage and transmission.



def decrypt_password(key: bytes, encrypted_password: bytes) -> str:
    #This function decrypts the encrypted password and converts it back to a string.
    #This function uses the 'Fernet' decryption algorithm from the 'cryptography' library.
    #This function has two parameters. The first parameter is 'key' which is the
    #cryptographic key used for decryption. The second parameter is 'encrypted_password'
    #which is the encrypted password. This function is to return the decrypted passowrd as
    #a string.

    f = Fernet(key)
    #This assigns the variable 'f' to a Fernet cipher instance. This intializes a Fernet 
    #cipher with the given key. This must be the same key that is used during encryption.
    #The cipher handles both encryption and decryption because this is a symmetric encryption, 
    #meaning the same key is used for both processes.

    return f.decrypt(encrypted_password).decode()
    #This line decrypts the encrypted password and returns the password as a string value. The 
    #'f.decrypt(encrypted_password)' decrypts the encrypted password bytes using AES-128-CBC with
    #HMAC authentication. This also verifies the HMAC authentication tag to ensure that the data is
    #honest. If the data has been tampered with or the wrong key is used, then any exception will be
    #shown.